import React, { useState } from 'react';
import { X, Copy, Check, Download, FileText, Code, Feather } from 'lucide-react';
import { FactCheckResult } from '../types';

interface ExportModalProps {
  isOpen: boolean;
  onClose: () => void;
  result: FactCheckResult | null;
}

export const ExportModal: React.FC<ExportModalProps> = ({ isOpen, onClose, result }) => {
  const [activeTab, setActiveTab] = useState<'markdown' | 'json'>('markdown');
  const [copied, setCopied] = useState(false);

  if (!isOpen || !result) return null;

  const generateMarkdown = () => {
    return `# THE DAILY VERIFIER — SPECIAL FACT-CHECK DOSSIER
**Published:** ${new Date().toLocaleDateString()}
**Verdict Stamp:** ${result.verdict.toUpperCase()}
**Truth Barometer:** ${result.truth_percentage}%
**Investigated Lead:** "${result.claim_analyzed}"

============================================================

## I. EDITORIAL BOARD VERDICT
- **Classification:** ${result.verdict}
- **Confidence Rating:** ${result.truth_percentage}%
- **Framing/Bias Classification:** ${result.bias_rating || 'N/A'}

## II. EDITORIAL REASONING & SYNTHESIS
${result.reasoning}

## III. SOURCE DEPENDENCY & CREDIBILITY ANALYSIS
${result.dependency_analysis}

## IV. KEY INVESTIGATIVE EXHIBITS
${
  result.key_evidence && result.key_evidence.length > 0
    ? result.key_evidence.map((e) => `- [${e.type.toUpperCase()}] ${e.point}`).join('\n')
    : '_No discrete exhibits cataloged._'
}

## V. PRIMARY WIRE CITATIONS & BIBLIOGRAPHY
${
  result.sources && result.sources.length > 0
    ? result.sources.map((s, idx) => `${idx + 1}. **${s.title}** (Tier ${s.domain_tier})\n   - Wire URL: ${s.url}\n   - Excerpt: ${s.snippet || 'N/A'}`).join('\n\n')
    : '_No external dispatches cited._'
}

============================================================
*Generated by SahiKya Press with Gemini 3.7 & Real-Time Google Search Grounding.*
`;
  };

  const markdownContent = generateMarkdown();
  const jsonContent = JSON.stringify(result, null, 2);
  const activeContent = activeTab === 'markdown' ? markdownContent : jsonContent;

  const handleCopy = () => {
    navigator.clipboard.writeText(activeContent);
    setCopied(true);
    setTimeout(() => setCopied(false), 2000);
  };

  const handleDownload = () => {
    const ext = activeTab === 'markdown' ? 'md' : 'json';
    const mime = activeTab === 'markdown' ? 'text/markdown' : 'application/json';
    const blob = new Blob([activeContent], { type: mime });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = `daily-verifier-dossier-${Date.now()}.${ext}`;
    document.body.appendChild(a);
    a.click();
    document.body.removeChild(a);
    URL.revokeObjectURL(url);
  };

  return (
    <div className="fixed inset-0 z-50 flex items-center justify-center p-4 bg-black/75 backdrop-blur-xs animate-fadeIn">
      <div className="w-full max-w-3xl max-h-[85vh] newsprint-paper border-4 border-[#1c1917] shadow-[8px_8px_0px_#1c1917] flex flex-col overflow-hidden text-[#1c1917]">
        {/* Modal Header */}
        <div className="px-6 py-4 border-b-2 border-[#1c1917] flex items-center justify-between bg-[#f4eee1]">
          <div className="flex items-center space-x-3">
            <div className="p-1.5 bg-[#1c1917] text-[#fdfbf7]">
              <FileText className="w-5 h-5" />
            </div>
            <div>
              <h2 className="font-headline font-bold text-base sm:text-lg text-[#1c1917] uppercase">
                Export Gazette Dossier
              </h2>
              <p className="font-typewriter text-xs text-[#57534e]">
                Download or archive fact-checking transcripts in standard newsroom formats.
              </p>
            </div>
          </div>

          <button
            onClick={onClose}
            className="p-1 border border-[#1c1917] bg-[#fdfbf7] text-[#1c1917] hover:bg-[#1c1917] hover:text-[#fdfbf7] transition cursor-pointer"
          >
            <X className="w-5 h-5" />
          </button>
        </div>

        {/* Tab Switcher */}
        <div className="px-6 py-2.5 border-b border-[#1c1917] flex items-center space-x-2 bg-[#fcf9f2]">
          <button
            onClick={() => setActiveTab('markdown')}
            className={`flex items-center space-x-1.5 px-3 py-1 text-xs font-typewriter font-bold transition cursor-pointer ${
              activeTab === 'markdown'
                ? 'bg-[#1c1917] text-[#fdfbf7]'
                : 'text-[#44403c] hover:text-[#1c1917]'
            }`}
          >
            <FileText className="w-3.5 h-3.5" />
            <span>Markdown Broadsheet (.md)</span>
          </button>

          <button
            onClick={() => setActiveTab('json')}
            className={`flex items-center space-x-1.5 px-3 py-1 text-xs font-typewriter font-bold transition cursor-pointer ${
              activeTab === 'json'
                ? 'bg-[#1c1917] text-[#fdfbf7]'
                : 'text-[#44403c] hover:text-[#1c1917]'
            }`}
          >
            <Code className="w-3.5 h-3.5" />
            <span>Telegraph JSON (.json)</span>
          </button>
        </div>

        {/* Content Viewer */}
        <div className="flex-1 p-4 overflow-y-auto font-typewriter text-xs bg-[#f4eee1] text-[#1c1917] select-all">
          <pre className="p-4 bg-[#fcf9f2] border border-[#1c1917] whitespace-pre-wrap leading-relaxed shadow-inner">
            {activeContent}
          </pre>
        </div>

        {/* Actions */}
        <div className="px-6 py-3 border-t-2 border-[#1c1917] bg-[#f4eee1] flex items-center justify-between">
          <span className="text-xs text-[#57534e] font-typewriter">
            Archival Gazette Edition
          </span>

          <div className="flex items-center space-x-3">
            <button
              onClick={handleCopy}
              className="flex items-center space-x-1.5 px-4 py-2 bg-[#fdfbf7] hover:bg-[#efe6d5] border border-[#1c1917] text-xs font-typewriter font-bold text-[#1c1917] transition shadow-[2px_2px_0px_#1c1917] cursor-pointer"
            >
              {copied ? <Check className="w-4 h-4 text-[#166534]" /> : <Copy className="w-4 h-4" />}
              <span>{copied ? 'Copied to Clipboard' : 'Copy Content'}</span>
            </button>

            <button
              onClick={handleDownload}
              className="flex items-center space-x-1.5 px-4 py-2 bg-[#1c1917] hover:bg-[#292524] text-[#fdfbf7] text-xs font-typewriter font-bold uppercase shadow-[2px_2px_0px_#78716c] transition cursor-pointer"
            >
              <Download className="w-4 h-4" />
              <span>Download Dossier</span>
            </button>
          </div>
        </div>
      </div>
    </div>
  );
};

