// Standalone Python Streamlit App Code Export

export const STREAMLIT_APP_LINES = [
  '"""',
  'News Verification and Fact-Checking Dashboard',
  'Tech Stack: Streamlit, Google Gemini API (gemini-3.6-flash / gemini-3.7-flash), Tavily AI API',
  '"""',
  '',
  'import os',
  'import json',
  'import re',
  'from typing import Dict, Any, List',
  'import streamlit as st',
  'from google import genai',
  'from google.genai import types',
  '',
  '# ============================================================================== #',
  '# API KEY CONFIGURATION                                                          #',
  '# ============================================================================== #',
  '# Set your API keys as environment variables before running:',
  '# export GEMINI_API_KEY="your_gemini_api_key_here"',
  '# export TAVILY_API_KEY="your_tavily_api_key_here"',
  '# Or provide them directly in the Streamlit sidebar.',
  '',
  'GEMINI_API_KEY = os.environ.get("GEMINI_API_KEY", "")',
  'TAVILY_API_KEY = os.environ.get("TAVILY_API_KEY", "")',
  '',
  '# Page Configuration',
  'st.set_page_config(',
  '    page_title="FactCheck AI | News Verification Dashboard",',
  '    page_icon="🔍",',
  '    layout="wide",',
  '    initial_sidebar_state="expanded"',
  ')',
  '',
  '# Custom CSS for Sleek Newsroom Interface',
  'st.markdown("""',
  '<style>',
  '    .main { background-color: #0f172a; color: #f8fafc; }',
  '    .stMetric {',
  '        background: #1e293b;',
  '        padding: 18px;',
  '        border-radius: 12px;',
  '        border: 1px solid #334155;',
  '    }',
  '    .verdict-true {',
  '        background: #065f46; color: #ecfdf5; padding: 18px;',
  '        border-radius: 12px; border: 2px solid #10b981;',
  '        text-align: center; font-weight: 800; font-size: 24px;',
  '    }',
  '    .verdict-false {',
  '        background: #881337; color: #fff1f2; padding: 18px;',
  '        border-radius: 12px; border: 2px solid #f43f5e;',
  '        text-align: center; font-weight: 800; font-size: 24px;',
  '    }',
  '    .verdict-misleading {',
  '        background: #78350f; color: #fffbeb; padding: 18px;',
  '        border-radius: 12px; border: 2px solid #f59e0b;',
  '        text-align: center; font-weight: 800; font-size: 24px;',
  '    }',
  '    .verdict-unverifiable {',
  '        background: #334155; color: #f1f5f9; padding: 18px;',
  '        border-radius: 12px; border: 2px solid #64748b;',
  '        text-align: center; font-weight: 800; font-size: 24px;',
  '    }',
  '</style>',
  '""", unsafe_allow_html=True)',
  '',
  '# ============================================================================== #',
  '# SEARCH & VERIFICATION LOGIC                                                    #',
  '# ============================================================================== #',
  '',
  'def search_tavily(query: str, api_key: str) -> List[Dict[str, Any]]:',
  '    """Execute live web search using Tavily AI API."""',
  '    import urllib.request',
  '    if not api_key:',
  '        return []',
  '    url = "https://api.tavily.com/search"',
  '    payload = {',
  '        "api_key": api_key,',
  '        "query": query,',
  '        "search_depth": "advanced",',
  '        "max_results": 6,',
  '        "topic": "news"',
  '    }',
  '    try:',
  '        req = urllib.request.Request(',
  '            url,',
  '            data=json.dumps(payload).encode("utf-8"),',
  '            headers={"Content-Type": "application/json"}',
  '        )',
  '        with urllib.request.urlopen(req, timeout=12) as response:',
  '            data = json.loads(response.read().decode("utf-8"))',
  '            return data.get("results", [])',
  '    except Exception as e:',
  '        st.warning(f"Tavily search notice: {e}. Falling back to Google Search grounding.")',
  '        return []',
  '',
  '',
  'def verify_claim_with_gemini(raw_input: str, gemini_key: str, tavily_key: str) -> Dict[str, Any]:',
  '    """Main fact-checking pipeline with Google GenAI SDK & Google Search tool."""',
  '    if not gemini_key:',
  '        raise ValueError("GEMINI_API_KEY is required.")',
  '',
  '    ai_client = genai.Client(api_key=gemini_key)',
  '',
  '    # 1. Extract core claim',
  '    claim_prompt = (',
  '        "Extract the single core factual claim from the following news statement or URL text. "',
  '        "Output ONLY the concise factual claim as a single clear sentence:\\n\\n" + raw_input',
  '    )',
  '    claim_res = ai_client.models.generateContent(',
  '        model="gemini-2.5-flash",',
  '        contents=claim_prompt',
  '    )',
  '    extracted_claim = claim_res.text.strip() if claim_res.text else raw_input.strip()',
  '',
  '    # 2. Gather live web evidence via Tavily (if configured)',
  '    tavily_results = search_tavily(extracted_claim, tavily_key) if tavily_key else []',
  '    tavily_context = ""',
  '    if tavily_results:',
  '        tavily_context = "\\n\\n--- TAVILY LIVE WEB RESULTS ---\\n" + "\\n".join([',
  '            f"Title: {r.get(\'title\')}\\nURL: {r.get(\'url\')}\\nContent: {r.get(\'content\')}"',
  '            for r in tavily_results',
  '        ])',
  '',
  '    # 3. Impartial Fact-Checking Synthesis',
  '    system_instruction = (',
  '        "You are an impartial, elite investigative journalist and senior fact-checker. "',
  '        "Cross-examine claims strictly against live web facts, primary documentation, and Tier-1 wire services (AP, Reuters, AFP, BBC).\\n\\n"',
  '        "STRICT JSON OUTPUT REQUIREMENT:\\n"',
  '        "Return ONLY a valid JSON object with the following fields:\\n"',
  '        "- claim_analyzed: string (the specific claim tested)\\n"',
  '        "- verdict: string (EXACTLY one of: \'True\', \'False\', \'Misleading\', \'Unverifiable\')\\n"',
  '        "- truth_percentage: float (confidence from 0.0 to 100.0 rounded to one decimal place, e.g. 85.5)\\n"',
  '        "- reasoning: string (a concise, objective paragraph explaining the verdict based on evidence)\\n"',
  '        "- dependency_analysis: string (evaluation of source credibility, e.g., \'Relies heavily on Tier-1 wire services\')\\n"',
  '        "- sources: list of objects with title, url, domain_tier (1 for wire/primary, 2 for mainstream, 3 for blog), and snippet"',
  '    )',
  '',
  '    synthesis_prompt = f"Claim to Verify: \\"{extracted_claim}\\"\\n\\nOriginal Input:\\n{raw_input}\\n{tavily_context}\\n\\nVerify this claim now using live web search and return structured JSON."',
  '',
  '    response = ai_client.models.generateContent(',
  '        model="gemini-3.7-flash",',
  '        contents=synthesis_prompt,',
  '        config=types.GenerateContentConfig(',
  '            system_instruction=system_instruction,',
  '            tools=[types.Tool(google_search=types.GoogleSearch())],',
  '            response_mime_type="application/json"',
  '        )',
  '    )',
  '',
  '    raw_text = response.text or "{}"',
  '    cleaned = re.sub(r"^```json\\s*", "", raw_text.strip(), flags=re.MULTILINE)',
  '    cleaned = re.sub(r"\\s*```$", "", cleaned.strip(), flags=re.MULTILINE)',
  '    parsed = json.loads(cleaned)',
  '',
  '    # Augment with Google Search Grounding URLs if present',
  '    grounding_chunks = (',
  '        response.candidates[0].grounding_metadata.grounding_chunks',
  '        if response.candidates and response.candidates[0].grounding_metadata',
  '        else []',
  '    )',
  '    if grounding_chunks and "sources" in parsed:',
  '        seen = {s.get("url") for s in parsed.get("sources", [])}',
  '        for chunk in grounding_chunks:',
  '            if hasattr(chunk, "web") and chunk.web and chunk.web.uri:',
  '                if chunk.web.uri not in seen:',
  '                    parsed["sources"].append({',
  '                        "title": chunk.web.title or "Verified Web Citation",',
  '                        "url": chunk.web.uri,',
  '                        "domain_tier": 1 if any(w in chunk.web.uri for w in ["reuters", "apnews", "gov", "edu"]) else 2,',
  '                        "snippet": "Retrieved via Google Search Grounding"',
  '                    })',
  '',
  '    if "truth_percentage" in parsed:',
  '        try:',
  '            parsed["truth_percentage"] = round(float(parsed["truth_percentage"]), 1)',
  '        except (ValueError, TypeError):',
  '            parsed["truth_percentage"] = 50.0',
  '',
  '    return parsed',
  '',
  '# ============================================================================== #',
  '# STREAMLIT USER INTERFACE                                                       #',
  '# ============================================================================== #',
  '',
  'def main():',
  '    st.title("🔍 News Verification & Fact-Checking Dashboard")',
  '    st.caption("Impartial AI-powered investigative intelligence grounded in live web & wire data.")',
  '',
  '    with st.sidebar:',
  '        st.header("⚙️ Configuration")',
  '        user_gemini_key = st.text_input("Gemini API Key", value=GEMINI_API_KEY, type="password")',
  '        user_tavily_key = st.text_input("Tavily API Key (Optional)", value=TAVILY_API_KEY, type="password")',
  '        st.markdown("---")',
  '        st.markdown("**Tier 1:** Primary Outlets & Wire Services (AP, Reuters, .gov)")',
  '        st.markdown("**Tier 2:** Mainstream Verified Media (BBC, NYT, WSJ)")',
  '        st.markdown("**Tier 3:** Secondary Blogs / Aggregators")',
  '',
  '    with st.form("factcheck_form"):',
  '        user_text = st.text_area(',
  '            "Enter a news claim, headline, article excerpt, or URL:",',
  '            height=130,',
  '            placeholder="e.g. \'NASA detected water vapor on an exoplanet in the habitable zone\'"',
  '        )',
  '        submitted = st.form_submit_button("⚡ Run Full Fact-Check", use_container_width=True)',
  '',
  '    if submitted:',
  '        if not user_text.strip():',
  '            st.error("Please enter a claim to verify.")',
  '            return',
  '        active_key = user_gemini_key or os.environ.get("GEMINI_API_KEY")',
  '        if not active_key:',
  '            st.error("Missing GEMINI_API_KEY. Please provide it in the sidebar.")',
  '            return',
  '        with st.spinner("Investigating against live wire reports and citations..."):',
  '            try:',
  '                res = verify_claim_with_gemini(user_text, active_key, user_tavily_key)',
  '                verdict = res.get("verdict", "Unverifiable")',
  '                truth_pct = res.get("truth_percentage", 50.0)',
  '                st.markdown("---")',
  '                col1, col2 = st.columns([2, 1])',
  '                with col1:',
  '                    st.markdown(f"### Analyzed Claim: *{res.get(\'claim_analyzed\', user_text)}*")',
  '                    css_class = f"verdict-{verdict.lower()}"',
  '                    st.markdown(f"<div class=\'{css_class}\'>VERDICT: {verdict.upper()}</div>", unsafe_allow_html=True)',
  '                with col2:',
  '                    st.metric("Truth Confidence", f"{truth_pct}%")',
  '                    st.progress(float(truth_pct) / 100.0)',
  '                st.markdown("### 📝 Investigative Reasoning")',
  '                st.write(res.get("reasoning", "No reasoning returned."))',
  '                st.markdown("### 🛡️ Dependency Analysis")',
  '                st.caption(res.get("dependency_analysis", "Analyzed using live search."))',
  '                st.markdown("### 🔗 Citations")',
  '                for s in res.get("sources", []):',
  '                    st.markdown(f"- **{s.get(\'title\')}** (Tier {s.get(\'domain_tier\', 2)}): [{s.get(\'url\')}]({s.get(\'url\')})")',
  '                with st.expander("📦 Structured JSON"):',
  '                    st.json(res)',
  '            except Exception as err:',
  '                st.error(f"Investigation failed: {err}")',
  '',
  'if __name__ == "__main__":',
  '    main()',
];

export const STREAMLIT_APP_CODE = STREAMLIT_APP_LINES.join('\n');
